# Ejemplos

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Eva", 
    "edad": 20 
}

### 

POST https://api-mongodb-dev-sedb.2.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jose", 
    "edad": 21 
}


### 

GET https://api-mongodb-dev-sedb.2.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

###

GET https://api-mongodb-dev-sedb.2.us-1.fl0.io/api/users/654a78e5824a0f6204d35762 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/users/6548f6566802ae8e19bd782b HTTP/1.1
content-type: application/json

{ 
    "nombre": "José Antonio", 
    "edad": 32 
}

###

DELETE https://api-mongodb-dev-sedb.2.us-1.fl0.io/api/users/654a6bcd318aaacb68ca6fe8 HTTP/1.1
content-type: application/json

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/users/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json
